image: registry.gitlab.fpcomplete.com/fpco/default-build-image:17

cache:
  key: "$CI_BUILD_NAME"
  paths:
    - .stack-work/
    - http-client/.stack-work/
    - http-client-tls/.stack-work/
    - http-conduit/.stack-work/
    - .stack-root/

stages:
  - build

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

build:
  stage: build
  script:
    - stack build --install-ghc http-conduit # just for nicer CI output
    - ./integration-test.hs
    - ./integration-test
